### ISSUE TITLE
Request to use your project for personal project

### ISSUE THREAD

**Issue by RuneShell** [helayzhang/utf8unicode#1]
Hello there.
I found your project nicely converts utf8 to unicode during my search. If you don't mind, I would like to include it as part of my personal project. Thank you for your time and consideration.

**Comment by helayzhang** [comment]
I'm glad if this repo helps you. Never mind and you can use it for free.

**Comment by RuneShell** [comment]
Thank you so much for granting my request.
HLEEJ

2023년 4월 2일 (일) 오전 12:56, helayzhang ***@***.***>님이 작성:
